ALTER TABLE hackathons
    ALTER COLUMN date_of_register TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN date_of_start TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN date_of_end TYPE TIMESTAMP WITH TIME ZONE; 