ktor:
    application:
        modules:
            - com.hacksync.general.ApplicationKt.module
    deployment:
        port: 8080
    db:
      url: "jdbc:postgresql://127.0.0.1:5432/postgres"
      user: postgres
      password: mysecretpassword
    jwt:
      secret: "your-256-bit-secret-key-here-must-be-at-least-32-characters-long"
      issuer: "https://localhost:8080"
      audience: "hacksync-api"
      accessTokenExpiry: "1000 * 60"
      refreshTokenExpiry: "24 * 60 * 60 * 1000" # 24 hours
      realm: "hacksync-realm"
      expiration: 86400