ktor:
    application:
        modules:
            - com.hacksync.general.ApplicationKt.module
    deployment:
        port: 8080
    db:
      url: "jdbc:postgresql://127.0.0.1:5432/postgres"
      user: postgres
      password: mysecretpassword
      passwordjwt: secret
      domain: "https://jwt-provider-domain/"
      audience: "jwt-audience"
      realm: "ktor sample app"
